version: '3'

services:
  app:
    image: "ghcr.io/samanthavbarron/healthkit-influxdb-grafana:main"
    ports:
      - "5353:5353"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=5353
      - VICTORIA_METRICS_HOST=victoriametrics
      - VICTORIA_METRICS_PORT=8428
    depends_on:
      - victoriametrics
    restart:
      unless-stopped

  victoriametrics:
    image: victoriametrics/victoria-metrics
    restart: unless-stopped
    ports:
      - "8428:8428"
    volumes:
      - victoriametrics_data:/victoria-metrics-data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
  
volumes:
  victoriametrics_data:
    driver: local
  grafana_data:
    driver: local
